#!/usr/bin/env python3
"""
Generate a compact Traditional→Simplified CJK remap table for the Simplified
Chinese firmware build (CHINESE_UI_SIMPLIFIED).

SC builtin fonts embed Simplified glyphs. Traditional EPUB/UI codepoints remap
via this table so we do not store duplicate SC/TC bitmaps.

Output: lib/EpdFont/TcToScRemap.h (committed; rebuilds do not need OpenCC).

Requires: pip install OpenCC
"""

from __future__ import annotations

import sys
from pathlib import Path

try:
    from opencc import OpenCC
except ImportError:
    print("error: OpenCC not installed. Run: pip install OpenCC", file=sys.stderr)
    sys.exit(1)

SCRIPT_DIR = Path(__file__).resolve().parent
OUTPUT_FILE = SCRIPT_DIR.parent / "TcToScRemap.h"

CJK_FIRST = 0x4E00
CJK_LAST = 0x9FFF


def build_pairs() -> list[tuple[int, int]]:
    cc = OpenCC("t2s")
    pairs: list[tuple[int, int]] = []
    for cp in range(CJK_FIRST, CJK_LAST + 1):
        sc = cc.convert(chr(cp))
        if len(sc) != 1:
            continue
        sc_cp = ord(sc)
        if sc_cp != cp and sc_cp <= 0xFFFF:
            pairs.append((cp, sc_cp))
    pairs.sort(key=lambda p: p[0])
    return pairs


def emit_header(pairs: list[tuple[int, int]]) -> str:
    lines = [
        "#pragma once",
        "// Auto-generated by lib/EpdFont/scripts/build_tc_to_sc_remap.py — do not edit.",
        "// Traditional→Simplified single-char map (OpenCC t2s) for CHINESE_UI_SIMPLIFIED.",
        "// Identity codepoints are omitted; callers binary-search then fall back to cp.",
        "",
        "#include <algorithm>",
        "#include <cstdint>",
        "",
        "struct TcToScEntry {",
        "  uint16_t tc;",
        "  uint16_t sc;",
        "};",
        "",
        f"static constexpr TcToScEntry kTcToScRemap[] = {{",
    ]
    for tc, sc in pairs:
        lines.append(f"    {{0x{tc:04X}, 0x{sc:04X}}},  // {chr(tc)} → {chr(sc)}")
    lines += [
        "};",
        "",
        f"static constexpr uint16_t kTcToScRemapCount = {len(pairs)};",
        "",
        "/// Map a Traditional CJK Unified Ideograph to Simplified when they differ.",
        "/// Non-CJK and unmapped codepoints are returned unchanged.",
        "inline uint32_t mapTraditionalToSimplified(uint32_t cp) {",
        "  if (cp < 0x4E00 || cp > 0x9FFF) {",
        "    return cp;",
        "  }",
        "  const auto target = static_cast<uint16_t>(cp);",
        "  const TcToScEntry* begin = kTcToScRemap;",
        "  const TcToScEntry* end = kTcToScRemap + kTcToScRemapCount;",
        "  const auto* it =",
        "      std::lower_bound(begin, end, target, [](const TcToScEntry& entry, uint16_t value) { return entry.tc < value; });",
        "  if (it != end && it->tc == target) {",
        "    return it->sc;",
        "  }",
        "  return cp;",
        "}",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    pairs = build_pairs()
    OUTPUT_FILE.write_text(emit_header(pairs), encoding="utf-8")
    print(
        f"Wrote {len(pairs)} TC→SC pairs ({len(pairs) * 4} bytes) to "
        f"{OUTPUT_FILE.relative_to(SCRIPT_DIR.parent.parent)}",
        file=sys.stderr,
    )


if __name__ == "__main__":
    main()
