#!/usr/bin/env python3
"""
Generate a compact Simplified→Traditional CJK remap table for the Chinese
firmware build.

The CN builtin fonts embed Traditional glyphs only (GenSen Rounded TW). UI
strings and many EPUBs still use Simplified codepoints; EpdFont::getGlyph
remaps via this table so we do not store duplicate SC/TC bitmaps.

Output: lib/EpdFont/ScToTcRemap.h (committed; rebuilds do not need OpenCC).

Requires: pip install OpenCC
"""

from __future__ import annotations

import sys
from pathlib import Path

try:
    from opencc import OpenCC
except ImportError:
    print("error: OpenCC not installed. Run: pip install OpenCC", file=sys.stderr)
    sys.exit(1)

SCRIPT_DIR = Path(__file__).resolve().parent
OUTPUT_FILE = SCRIPT_DIR.parent / "ScToTcRemap.h"

# CJK Unified Ideographs (BMP). Extension A/B are out of scope for the
# uint16_t table; rare chars there fall through as identity.
CJK_FIRST = 0x4E00
CJK_LAST = 0x9FFF


def build_pairs() -> list[tuple[int, int]]:
    cc = OpenCC("s2t")
    pairs: list[tuple[int, int]] = []
    for cp in range(CJK_FIRST, CJK_LAST + 1):
        tc = cc.convert(chr(cp))
        if len(tc) != 1:
            continue
        tc_cp = ord(tc)
        # Remap table is uint16_t×uint16_t; drop rare Extension-B targets.
        if tc_cp != cp and tc_cp <= 0xFFFF:
            pairs.append((cp, tc_cp))
    pairs.sort(key=lambda p: p[0])
    return pairs


def emit_header(pairs: list[tuple[int, int]]) -> str:
    lines = [
        "#pragma once",
        "// Auto-generated by lib/EpdFont/scripts/build_sc_to_tc_remap.py — do not edit.",
        "// Simplified→Traditional single-char map (OpenCC s2t) for ENABLE_CHINESE_VERSION.",
        "// Identity codepoints are omitted; callers binary-search then fall back to cp.",
        "",
        "#include <cstdint>",
        "",
        "#include <algorithm>",
        "",
        "struct ScToTcEntry {",
        "  uint16_t sc;",
        "  uint16_t tc;",
        "};",
        "",
        f"static constexpr ScToTcEntry kScToTcRemap[] = {{",
    ]
    for sc, tc in pairs:
        lines.append(f"    {{ 0x{sc:04X}, 0x{tc:04X} }},  // {chr(sc)} → {chr(tc)}")
    lines += [
        "};",
        "",
        f"static constexpr uint16_t kScToTcRemapCount = {len(pairs)};",
        "",
        "/// Map a Simplified CJK Unified Ideograph to Traditional when they differ.",
        "/// Non-CJK and unmapped codepoints are returned unchanged.",
        "inline uint32_t mapSimplifiedToTraditional(uint32_t cp) {",
        "  if (cp < 0x4E00 || cp > 0x9FFF) {",
        "    return cp;",
        "  }",
        "  const auto target = static_cast<uint16_t>(cp);",
        "  const ScToTcEntry* begin = kScToTcRemap;",
        "  const ScToTcEntry* end = kScToTcRemap + kScToTcRemapCount;",
        "  const auto* it = std::lower_bound(",
        "      begin, end, target,",
        "      [](const ScToTcEntry& entry, uint16_t value) { return entry.sc < value; });",
        "  if (it != end && it->sc == target) {",
        "    return it->tc;",
        "  }",
        "  return cp;",
        "}",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    pairs = build_pairs()
    OUTPUT_FILE.write_text(emit_header(pairs), encoding="utf-8")
    print(
        f"Wrote {len(pairs)} SC→TC pairs ({len(pairs) * 4} bytes) to "
        f"{OUTPUT_FILE.relative_to(SCRIPT_DIR.parent.parent)}",
        file=sys.stderr,
    )


if __name__ == "__main__":
    main()
